```{r}
#Naufal Rasyid Sutansyah
library(readr)
library(tidyr)
library(psych)
library(ggplot2)
library(tidyverse)
library(effectsize)
library(rcompanion)

#Load Dataset
setwd('C:/Users/LENOVO THINKPAD T460/Downloads/archive')
getwd()

data <- read_csv('supermarket_sales.csv')

```


```{r}
#Melihat melihat 6 baris awal data
head(data)
```

```{r}
#Melihat struktur data#
str(data)
```


```{r}
#Check missing data
sum(is.na(data))#jumlah semua
```


```{r}
#Cek duplikat data
sum(duplicated(data))
sapply(data,function(x) table(as.character(x) =="")["TRUE"])
summary(is.na(data))  # To check null values
```


```{r}
summary(data)

```

```{r}
#standar deviasi setiap variabel numeric
variables <- c("Unit price", "Quantity", "Tax 5%", "Total", "cogs", "gross margin percentage", "gross income", "Rating")

# Calculate and print the standard deviation for each variable
for (variable in variables) {
  sd_value <- sd(data[[variable]])
  cat("standart deviation", variable, ": ", sd_value, "\n")
}

```

```{r}
#Correlation analyis Dependant Rating(ordinal) ~ Independant ~ Branch, City, Gender, Customer type, Time, Product Line, Payment, Total
```

```{r}
# Calculate Spearman correlation Dependant Rating(ordinal) ~ Total (Continous)
cor(data$Rating, data$Total, method = "spearman")
```
```{r}
# Calculate Spearman correlation Dependant Rating(ordinal) ~ Time (Continous)
cor(as.numeric(data$Time),data$Rating, method = "spearman")

```

```{r}
# Calculate Rank biserial correlation Dependant Rating(ordinal) ~ Gender (Nominal) using library effectsize

binary_Gender <- as.factor(data$Gender == "Female")
cat("Binary Gender variable:", binary_Gender, "\n")
# Calculate Rank biserial correlation
cor_gender<- rank_biserial(Rating ~ binary_Gender, data = data)
cor_gender
```

```{r}
# Calculate rank biserial correlation Dependant Rating(ordinal) ~ Customer Type(Continous) using library effectsize
customer <- as.factor(data$`Customer type` == "Member")
cat("Binary Customer variable:", customer, "\n")
# Calculate Rank biserial correlation
cor_customer<- rank_biserial(Rating ~ customer, data = data)
cor_customer
```

```{r}
# Calculate Rank biserial correlation Dependant Rating(ordinal) ~ Branch (Nominal)using library rcompanion

# Create a factor variable for Branch
branch <- as.factor(data$Branch)
cat("Binary Gender variable:", branch, "\n")
# Calculate rank biserial correlation
cor_branch <- wilcoxonRG(x = data$Rating, g = branch)
cor_branch
```
```{r}
# Calculate Rank biserial correlation Dependant Rating(ordinal) ~ City (Nominal)using library rcompanion

city <- as.factor(data$City)
cat("Binary Gender variable:", city, "\n")
# Calculate rank biserial correlation
cor_city <- wilcoxonRG(x = data$Rating, g = city)
cor_city
```
```{r}
# Calculate Rank biserial correlation Dependant Rating(ordinal) ~ Payment (Nominal)using library rcompanion

payment <- as.factor(data$Payment)
cat("Binary payment variable:", payment, "\n")
# Calculate rank biserial correlation
cor_payment <- wilcoxonRG(x = data$Rating, g = payment)
cor_payment
```
```{r}
#Vizualisation
```

```{r}
#Scater Plot dataset data
plot(data)

```
```{r}
numericVar <- c("Unit price", "Quantity", "Tax 5%", "Total", "cogs", "gross margin percentage", "Rating")

for (n in numericVar) {
  hist(data[[n]], main = paste("Histogram of", n), xlab = n)
}
```

```{r}
#Branch
ggplot(data = data, aes(x = Branch, fill = Branch)) +
  geom_bar() +
  geom_text(stat = 'count', aes(label = stat(count)), vjust = -0.25) +
  labs(title = "Analisis Branch",
       subtitle = "Branch dengan pengujung terbanyak",
       x = "Branch",
       y = "Count") +
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#D55E00")) +
  theme_minimal()
```
```{r}
table(data$Branch, data$Gender)
```


```{r}
ggplot(data = data, aes(x = Branch, fill = Gender)) +
  geom_bar(position = "dodge") +
  labs(title = "Analis Branch",
       subtitle = "Branches with Gender Distribution",
       x = "Branch",
       y = "Count") +
  scale_fill_manual(values = c("#E69F00", "#56B4E9")) +
  theme_minimal()
```
```{r}
table(data$`Product line`, data$Branch)
```

```{r}
ggplot(data = data, aes(x = Branch, fill = `Product line`)) +
  geom_bar(position = "dodge") +
  labs(title = "Analisis Branch by Product",
       subtitle = "Branch with Product Line Distribution",
       x = "Branch",
       y = "Count")  +
  theme_minimal()
```
```{r}
#Branch
# Calculate total spend per branch
total_spend <- aggregate(Total ~ Branch, data = data, sum)

# Plot total spend per branch
ggplot(data = total_spend, aes(x = Branch, y = Total)) +
  geom_bar(stat = "identity", fill = c("#E69F00", "#56B4E9", "#D55E00")) +
  labs(title = "Total Spend per Branch",
       x = "Branch",
       y = "Total Spend") +
  theme_minimal()

#Branch C leads in revenue compared to brand B and brand A
```

```{r}
ggplot(data = data %>% group_by(Branch) %>% summarize(Total = sum(Total)), aes(x = Branch, y = Total, fill = Branch)) +
  geom_bar(stat = "identity") +
  labs(title = "Total Income per Branch",
       x = "Branch",
       y = "Total Income") +
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#D55E00")) +
  theme_minimal()
```

```{r}
ggplot(data = data, aes(x = Branch, fill = `Product line`)) +
  geom_bar(position = "dodge") +
  labs(title = "Analisis Branch by Product",
       subtitle = "Branch with Product Line Distribution",
       x = "Branch",
       y = "Count") +
  theme_minimal() +
  coord_flip()
```

```{r}
#Mayoritas Gender customer
ggplot(data = data, aes(x = Gender)) +
  geom_bar(aes(fill = Gender)) + 
  geom_text(stat = 'count', aes(label = stat(count)), vjust = -0.25) +
  labs(title = "Analisis Gender",
       subtitle = "Gender terbanyak?.",
       x = "Gender",
       y = "Count")+
  scale_fill_manual(values = c("#E69F00", "#56B4E9")) +
  theme_minimal()

```
```{r}
table(data$`Customer type`, data$Gender)
```

```{r}
ggplot(data = data, aes(x = Gender, fill = `Customer type`)) +
  geom_bar(position = "dodge") +
  labs(title = "Analisis Gender by Member Type",
       subtitle = "Branch with Member Type Distribution",
       x = "Gender",
       y = "Count") + scale_fill_manual(values = c("#E69F00", "#56B4E9")) +
  theme_minimal()
```


```{r}
table(data$`Product line`, data$Gender)
```

```{r}
ggplot(data = data, aes(x = Gender, fill = `Product line`)) +
  geom_bar(position = "dodge") +
  labs(title = "Analisis Gender by Product",
       subtitle = "Branch with Product Line Distribution",
       x = "Gender",
       y = "Count") +
  theme_minimal()
```

```{r}
#Payment Method paling sering dipakai
ggplot(data = data, aes(x = Payment)) +
  geom_bar(aes(fill = Payment)) + 
  geom_text(stat = 'count', aes(label = stat(count)), vjust = -0.25) +
  labs(title = "Analisis Payment",
       subtitle = "Payment paling sering?.",
       x = "Payment",
       y = "Count")+
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#D55E00")) +
  theme_minimal()

```
```{r}
table(data$Payment, data$Gender)
```

```{r}
ggplot(data = data, aes(x = Payment, fill = Gender)) +
  geom_bar(position = "dodge") + 
  labs(title = "Analisis Payment by Gender",
       subtitle = "Payment with Gender Distribution",
       x = "Payment",
       y = "Count")  +
  scale_fill_manual(values = c("#E69F00", "#56B4E9")) +
  theme_minimal()
```
```{r}
table(data$`Product line`, data$Payment)
```

```{r}
ggplot(data = data, aes(x = Payment, fill = `Product line`)) +
  geom_bar(position = "dodge") +
  labs(title = "Analisis Payment by Product",
       subtitle = "Payment with Product Line Distribution",
       x = "Payment",
       y = "Count")  +
  theme_minimal()

```
```{r}
table(data$Payment, data$Branch)
```

```{r}
ggplot(data = data, aes(x = Payment, fill = Branch)) +
  geom_bar(position = "dodge") +
  labs(title = "Analisis Payment by Branch",
       subtitle = "Payment with Branch Distribution",
       x = "Payment",
       y = "Count")  +
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#D55E00")) +
  theme_minimal()
  
```

```{r}
table(data$City,data$Payment)
```

```{r}
ggplot(data = data, aes(x = Payment, fill = City)) +
  geom_bar(position = "dodge") +
  labs(title = "Analisis Payment by City",
       subtitle = "Payment with City Distribution",
       x = "Payment",
       y = "Count")  +
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#D55E00")) +
  theme_minimal()
  
```

```{r}
#waktu belajan paling sering
# mengubah time menjadi factor
Time <- factor(data$Time)

# Plot the bar chart
ggplot(data = data, aes(x = Time)) +
  geom_bar(fill = "#E69F00") +
  labs(title = "Analisis waktu belanja",
       subtitle = "Waktu belanja paling sering?",
       x = "Waktu Belanja",
       y = "Count") +
  theme_minimal()
```
```{r}
# Calculate the mean rating per branch
rating_branch <- data %>% 
  group_by(Branch) %>% 
  summarize(mean_rating = mean(Rating)) %>% 
  arrange(mean_rating)

# Print the rating per branch
(rating_branch)

```

```{r}
#plot
ggplot(data = data, aes(x = Branch, y = Rating, fill = Branch)) +
  geom_boxplot(color = "black", outlier.color = "black") +
  labs(title = "Analysis of Rating per Branch",
       x = "Branch",
       y = "Rating") +
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#D55E00")) +
  theme_minimal()
```
```{r}
# Calculate the mean rating per city
rating_city <- data %>% 
  group_by(City) %>% 
  summarize(mean_rating = mean(Rating)) %>% 
  arrange(mean_rating)

# Print the rating per city
(rating_city)
```

```{r}
#plot
ggplot(data = data, aes(x = City, y = Rating, fill = City)) +
  geom_boxplot(color = "black", outlier.color = "black") +
  labs(title = "Analysis of Rating per City",
       x = "City",
       y = "Rating") +
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#D55E00")) +
  theme_minimal()
```
```{r}
# Calculate the mean rating per gender
rating_gender <- data %>%
  group_by(Gender) %>%
  summarize(mean_rating = mean(Rating)) %>%
  arrange(mean_rating)

# Print rating per gender
(rating_gender)
```

```{r}
ggplot(data = data, aes(x = Gender, y = Rating, fill = Gender)) +
  geom_boxplot(color = "black", outlier.color = "black") +
  scale_fill_manual(values = c("#E69F00", "#56B4E9")) +
  labs(title = "Analysis of Rating per Gender",
       x = "Gender",
       y = "Rating") +
  theme_minimal()
```
```{r}
# Calculate the mean rating per 
rating_customer <- data %>%
  group_by(`Customer type`) %>%
  summarize(mean_rating = mean(Rating)) %>%
  arrange(mean_rating)

# Print rating per customer
(rating_customer)

```

```{r}
ggplot(data = data, aes(x = `Customer type`, y = Rating, fill = `Customer type`)) +
  geom_boxplot(color = "black", outlier.color = "black") +
  scale_fill_manual(values = c("#E69F00", "#56B4E9", "#D55E00")) +
  labs(title = "Analysis of Rating per Customer",
       x = "Customer",
       y = "Rating") +
  theme_minimal()
```

```{r}
# Calculate the mean rating per 
rating_product <- data %>%
  group_by(`Product line`) %>%
  summarize(mean_rating = mean(Rating)) %>%
  arrange(mean_rating)

# Print rating per customer
(rating_product)

```

```{r}
ggplot(data = data, aes(x = `Product line`, y = Rating, fill = `Product line`)) +
  geom_boxplot(color = "black", outlier.color = "black") +
  labs(title = "Analysis of Rating per Product",
       x = "Customer",
       y = "Rating") +
  theme_minimal()
```
```{r}
ggplot(data = data, aes(x = Branch, y = Rating)) +
  geom_point() +
  labs(title = "Relationship between Rating and Branch",
       x = "Branch",
       y = "Rating") +
  theme_minimal()

```

```{r}
ggplot(data = data, aes(x = City, y = Rating)) +
  geom_point() +
  labs(title = "Relationship between Rating and City",
       x = "City",
       y = "Rating") +
  theme_minimal()
```


```{r}
ggplot(data = data, aes(x = `Product line`, y = Rating)) +
  geom_point() +
  labs(title = "Relationship between Rating and Product",
       x = "Product",
       y = "Rating") +
  theme_minimal() 
```

```{r}
ggplot(data = data, aes(x = `Customer type`, y = Rating)) +
  geom_point() +
  labs(title = "Relationship between Rating and Customer",
       x = "customer",
       y = "Rating") +
  theme_minimal()
```

```{r}
ggplot(data = data, aes(x = Payment, y = Rating)) +
  geom_point() +
  labs(title = "Relationship between Rating and Customer",
       x = "payment",
       y = "Rating") +
  theme_minimal()
```

```{r}
#Modeling
```

```{r}
library(dplyr)
# Specify the columns to keep
columns_to_keep <- c("Branch", "City", "Customer type", "Gender", "Payment", "Total", "Time", "Rating")

# Create a new dataset with only the specified columns
new_dataset <- data %>%
  select(all_of(columns_to_keep))

# Convert categorical variables to factors
Branch <- as.factor(new_dataset$Branch)
City <- as.factor(new_dataset$City)
Customer <- as.factor(new_dataset$`Customer type`)
Gender <- as.factor(new_dataset$Gender)
Payment <- as.factor(new_dataset$Payment)
str(new_dataset)
sum(is.na(new_dataset))

```
```{r}
#Menggunakan random forest
library(randomForest)

# Convert categorical variables to factors
Branch <- as.factor(new_dataset$Branch)
City <- as.factor(new_dataset$City)
Customer <- as.factor(new_dataset$`Customer type`)
Gender <- as.factor(new_dataset$Gender)
Payment <- as.factor(new_dataset$Payment)

# Features (X) and label (y)
X <- new_dataset[, c("Branch", "City", "Customer type", "Gender", "Payment", "Total", "Time", "Rating")]
y <- new_dataset$Rating

# Split the data into train and test sets
set.seed(42)  # Set the random seed for reproducibility
train_indices <- sample(nrow(new_dataset), round(0.8 * nrow(new_dataset)))
X_train <- X[train_indices, ]
y_train <- y[train_indices]
X_test <- X[-train_indices, ]
y_test <- y[-train_indices]

# Random forest regressor model
rf_model <- randomForest(x = X_train, y = y_train, ntree = 100, random_state = 42)

# Predictions on the test data
y_pred <- predict(rf_model, newdata = X_test)

# Evaluation metrics
mae <- mean(abs(y_test - y_pred))
mse <- mean((y_test - y_pred)^2)
rmse <- sqrt(mse)
r2 <- 1 - sum((y_test - y_pred)^2) / sum((y_test - mean(y_test))^2)

# Print the evaluation metrics
cat("MAE:", mae, "\n")
cat("MSE:", mse, "\n")
cat("RMSE:", rmse, "\n")
cat("R-squared:", r2, "\n")
print(rf_model)
```
```{r}
# Load required libraries
library(nnet)

# Split the data into train and test sets
set.seed(42)  # Set the random seed for reproducibility
train_indices <- sample(nrow(new_dataset), round(0.8 * nrow(new_dataset)))
train_data <- new_dataset[train_indices, ]
test_data <- new_dataset[-train_indices, ]

# Create the neural network model
nn_model <- nnet(Rating ~ ., data = train_data, size = 10, decay = 0.1)

# Make predictions on the test data
predictions <- predict(nn_model, newdata = test_data)

# Evaluate the model
mae <- mean(abs(test_data$Rating - predictions))
mse <- mean((test_data$Rating - predictions)^2)
rmse <- sqrt(mse)
r_squared <- 1 - sum((test_data$Rating - predictions)^2) / sum((test_data$Rating - mean(test_data$Rating))^2)

# Print the evaluation metrics
cat("MAE:", mae, "\n")
cat("MSE:", mse, "\n")
cat("RMSE:", rmse, "\n")
cat("R-squared:", r_squared, "\n")
print(nn_model)
```

```{r}
library(e1071)  # Load the e1071 package for SVM modeling

set.seed(42)
train_indices <- sample(nrow(new_dataset), round(0.8 * nrow(new_dataset)))
train_data <- new_dataset[train_indices, ]
test_data <- new_dataset[-train_indices, ]

# SVM modeling
svm_model <- svm(Rating ~ ., data = train_data)

# Predictions on the test data
y_pred <- predict(svm_model, newdata = test_data)

# Evaluation metrics
mae <- mean(abs(test_data$Rating - y_pred))
mse <- mean((test_data$Rating - y_pred)^2)
rmse <- sqrt(mse)
rsquared <- 1 - sum((test_data$Rating - y_pred)^2) / sum((test_data$Rating - mean(test_data$Rating))^2)

# Print the evaluation metrics
cat("MAE:", mae, "\n")
cat("MSE:", mse, "\n")
cat("RMSE:", rmse, "\n")
cat("R-squared:", rsquared, "\n")
summary(svm_model)
```
```{r}
library(ggplot2)
library(viridis)


# Create a data frame with model names and R-squared scores
results_df <- data.frame(
  Model = c("Random Forest", "Neural Network", "SVM"),
  R2_Score = c(0.9312191, -11.51484, -0.08583694)
)

# Sort the data frame by R-squared score in descending order
results_df <- results_df[order(-results_df$R2_Score),]

# Plotting the bar plot
ggplot(results_df, aes(x = R2_Score, y = Model, fill = Model)) +
  geom_bar(stat = "identity", color = "black") +
  scale_fill_viridis(discrete = TRUE) +
  labs(title = "Model R2 Score Comparison",
       x = "R2 Score",
       y = "Model") +
  theme_minimal()

```

